name: sideswap_logger
description: Sideswap custom logger
version: 0.0.14

environment:
  sdk: ^3.10.3
  flutter: ^3.38.4

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
